/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_14C50693__
#define __PLUGINEDITOR_H_14C50693__

#include "../JuceLibraryCode/JuceHeader.h"
#include "../JuceLibraryCode/JucePluginCharacteristics.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class AutomelloPluginAudioProcessorEditor  : public AudioProcessorEditor, public ComboBoxListener
{
public:
    AutomelloPluginAudioProcessorEditor (AutomelloPluginAudioProcessor* ownerFilter);
    ~AutomelloPluginAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
  void resized();
  void comboBoxChanged( ComboBox *comboBoxThatHasChanged );
private:
  ComboBox directoryDropDown;
  File datasetDirectory;
  // Binary resources:
  static const char* logo320_png;
  static const int logo320_pngSize;
  Image logo;
  
  AutomelloPluginAudioProcessor* getProcessor() const
  {
    return static_cast <AutomelloPluginAudioProcessor*> (getAudioProcessor());
  }
};

#endif  // __PLUGINEDITOR_H_14C50693__
